version: '3.8'

services:
  f1_pipeline:
    build: .
    container_name: f1_strategy_container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8501:8501"
    tty: true
    stdin_open: true